@set #envtslogsss14280=5771184
@set allusersprofile=c:\programdata
@set appdata=c:\users\yu lei\appdata\roaming
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=lenovo-pc
@set comspec=c:\windows\system32\cmd.exe
@set configsetroot=c:\windows\configsetroot
@set crx_path_2015_x64=d:\program files\caxa\caxa cad\2015\crx\
@set devenvdir=c:\program files (x86)\microsoft visual studio 10.0\common7\ide\
@set easyplussdk="c:\program files (x86)\common files\lenovo\easyplussdk\bin"
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set fp_no_host_check=no
@set framework35version=v3.5
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft f#\v4.0\
@set genicam_cache_v2_1=d:\program files\jai\sdk\genicam\xml\cache
@set genicam_cache_v2_3=c:\program files (x86)\daheng imavision\mer-usbdevice\drivers\genicam\xml\cache
@set genicam_gentl32_path=c:\program files (x86)\daheng imavision\mer-usbdevice\drivers\merseries;c:\program files\allied vision technologies\vimba_2.1\vimba1394tl\bin\win32;c:\program files\allied vision technologies\vimba_2.1\vimbagigetl\bin\win32;c:\program files\allied vision technologies\vimba_2.1\vimbausbtl\bin\win32;c:\program files\allied vision technologies\vimba_2.1\vimbaclconfigtl\bin\win32
@set genicam_gentl64_path=c:\program files\allied vision technologies\vimba_2.1\vimba1394tl\bin\win64;c:\program files\allied vision technologies\vimba_2.1\vimbagigetl\bin\win64;c:\program files\allied vision technologies\vimba_2.1\vimbausbtl\bin\win64;c:\program files\allied vision technologies\vimba_2.1\vimbaclconfigtl\bin\win64
@set genicam_log_config_v2_1=d:\program files\jai\sdk\genicam\log\config\defaultlogging.properties
@set genicam_log_config_v2_3=c:\program files (x86)\daheng imavision\mer-usbdevice\drivers\genicam\log\config\debuglogging.properties
@set genicam_root_v2_1=d:\program files\jai\sdk\genicam
@set genicam_root_v2_3=c:\program files (x86)\daheng imavision\mer-usbdevice\drivers\genicam
@set halconarch=x86sse2-win32
@set halconexamples=c:\users\public\documents\mvtec\halcon-10.0\examples
@set halconimages=d:\program files\mvtec\halcon-10.0\images
@set halconroot=d:\program files\mvtec\halcon-10.0
@set homedrive=c:
@set homepath=\users\yu lei
@set include=c:\program files (x86)\microsoft visual studio 10.0\vc\include;c:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include;c:\program files (x86)\microsoft sdks\windows\v7.0a\include;D:\Program Files (x86)\Microsoft Visual Studio\VC98\atl\include;D:\Program Files (x86)\Microsoft Visual Studio\VC98\mfc\include;D:\Program Files (x86)\Microsoft Visual Studio\VC98\include
@set jaisdk_root=d:\program files\jai\sdk\
@set jai_sdk_bin=d:\program files\jai\sdk\bin\win32_i86
@set jai_sdk_bin_64=d:\program files\jai\sdk\bin
@set jai_sdk_data=d:\program files\jai\sdk\data
@set jai_sdk_debug=false
@set jai_sdk_include=d:\program files\jai\sdk\library\cpp\include
@set jai_sdk_lib=d:\program files\jai\sdk\library\cpp\lib\win32_i86
@set jai_sdk_lib_64=d:\program files\jai\sdk\library\cpp\lib\win64_x64
@set lib=c:\program files (x86)\microsoft visual studio 10.0\vc\lib;c:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\lib;c:\program files (x86)\microsoft sdks\windows\v7.0a\lib;D:\Program Files (x86)\Microsoft Visual Studio\VC98\mfc\lib;D:\Program Files (x86)\Microsoft Visual Studio\VC98\lib
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;c:\windows\microsoft.net\framework\v3.5;c:\program files (x86)\microsoft visual studio 10.0\vc\lib;c:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\lib
@set localappdata=c:\users\yu lei\appdata\local
@set logonserver=\\microsoftaccount
@set moz_plugin_path=c:\program files (x86)\foxit phantompdf\plugins\
@set msbuildsdkspath=c:\windows\microsoft.net\framework64\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set msdevdir=d:\program files (x86)\microsoft visual studio\common\msdev98
@set number_of_processors=4
@set onedrive=c:\users\yu lei\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft f#\v4.0\;c:\program files (x86)\microsoft visual studio 10.0\vstsdb\deploy;c:\program files (x86)\microsoft visual studio 10.0\common7\ide\;c:\program files (x86)\microsoft visual studio 10.0\vc\bin;c:\program files (x86)\microsoft visual studio 10.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;c:\windows\microsoft.net\framework\v3.5;c:\program files (x86)\microsoft visual studio 10.0\vc\vcpackages;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 10.0\team tools\performance tools;c:\program files (x86)\microsoft sdks\windows\v7.0a\bin\netfx 4.0 tools;c:\program files (x86)\microsoft sdks\windows\v7.0a\bin;c:\programdata\oracle\java\javapath;c:\program files (x86)\daheng imavision\mer-usbdevice\drivers\genicam\bin\win32_i86;c:\program files (x86)\daheng imavision\mer-usbdevice\drivers\merseries;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files (x86)\ati technologies\ati.ace\core-static;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\common files\lenovo\easyplussdk\bin;c:\programdata\lenovo\readyapps;c:\program files (x86)\microsoft sql server\100\tools\binn\;c:\program files\microsoft sql server\100\tools\binn\;c:\program files\microsoft sql server\100\dts\binn\;d:\program files\jai\sdk\bin;d:\program files\jai\sdk\bin\win32_i86;d:\program files\jai\sdk\genicam\bin\win64_x64;d:\program files\jai\sdk\genicam\bin\win32_i86;d:\program files\mvtec\halcon-10.0\bin\x86sse2-win32;d:\program files\mvtec\halcon-10.0\flexlm\x86sse2-win32;c:\users\yu lei\desktop\sc;c:\program files\microsoft sql server\110\tools\binn\;c:\program files\microsoft sql server\120\tools\binn\;c:\python36-32;d:\program files (x86)\microsoft visual studio\common\tools\winnt;d:\program files (x86)\microsoft visual studio\common\msdev98\bin;d:\program files (x86)\microsoft visual studio\common\tools;d:\program files (x86)\microsoft visual studio\vc98\bin;c:\python36-32
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 69 stepping 1, genuineintel
@set processor_level=6
@set processor_revision=4501
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\windows\microsoft.net\framework64\
@set qtdir=c:\qt\4.8.5
@set readyapps=c:\programdata\lenovo\readyapps
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\yulei~1\appdata\local\temp
@set tmp=c:\users\yulei~1\appdata\local\temp
@set tvt=c:\program files (x86)\lenovo
@set userdomain=lenovo-pc
@set userdomain_roamingprofile=lenovo-pc
@set username=yu lei
@set userprofile=c:\users\yu lei
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 10.0\vc\
@set vimba_home=c:\program files\allied vision technologies\vimba_2.1\
@set visualstudiodir=c:\users\yu lei\documents\visual studio 2010
@set vs100comntools=c:\program files (x86)\microsoft visual studio 10.0\common7\tools\
@set vs120comntools=d:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 10.0\
@set windir=c:\windows
@set windowssdkdir=c:\program files (x86)\microsoft sdks\windows\v7.0a\

@call "C:\Program Files (x86)\PVS-Studio\x86\clang.exe" --driver-mode=cl @"C:\Users\Yu Lei\OneDrive\Work\2.VISIO-C\GlasswareDetectSystem-VEXI-2.1.1.1\GlasswareDetectSystem\moc_widget_plc.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1